### PR TITLE
fix `examples` in json schema

### PR DESCRIPTION
**Pull request by trim21**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

fix https://github.com/fastify/fastify-swagger/issues/625

### CODE REVIEW

**Comment by mcollina** [comment]
I think we still need to support OpenAPI 3.0 too.

**Comment by trim21** [comment]
> I think we still need to support OpenAPI 3.0 too.

I don't think this will break openapi 3.0, it just didn't replace `examples` property in json schema object

**Review by climba03003 — CHANGES_REQUESTED** [review]
I would move the `examples` mutation to the proper place that should happen.

For example, [resolveResponse](https://github.com/fastify/fastify-swagger/blob/7546f2311c677a0a06acf112c0ebc8a50787e48d/lib/spec/openapi/utils.js#L318).
It can ensure, we are properly mutate the top-level only.

**Comment by trim21** [comment]
> I would move the `examples` mutation to the proper place that should happen.
> 
> For example, [resolveResponse](https://github.com/fastify/fastify-swagger/blob/7546f2311c677a0a06acf112c0ebc8a50787e48d/lib/spec/openapi/utils.js#L318). It can ensure, we are properly mutate the top-level only.

`transformDefsToComponents` is called on path, params, response and query, this will require to write it multiple times

**Comment by trim21** [comment]
I guess you want to move `examples` transform in `schemaToMedia`?

**Comment by climba03003** [comment]
Actually, `cookie`, `query`, `path`, `header` already doing it's own transform for the `properties.examples`. There are no need to mutate the `examples` for them.

For `body`, it reuse the same logic inside `schemaToMedia` which does require some mutation.

For `response`, it is the only one need to do more things.

**Comment by trim21** [comment]
I think this is what you are expecting?

**Review by climba03003 — APPROVED** [review]

**Review by Eomm — APPROVED** [review]

**Comment by trim21** [comment]
any releasing plan？ I'm currently encountering a openapi rendering issue will be fixed by this PR.

**Comment by Eomm** [comment]
Done in 8.2.1

**Pull request merged**
