### PR TITLE
make redirects from the swagger root relative

### PR DESCRIPTION
**Pull request by PavelPolyakov**
Resolves https://github.com/fastify/fastify-swagger/issues/241 .

Looking forward to your feedback.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by PavelPolyakov** [comment]
I don't know why tests fail and how to rerun them. Tried on my local with `12.16.3` - everything is ok. Also tried with `v10`. Any idea?

**Comment by PavelPolyakov** [comment]
k, after rebase I have these on my local, will fix

**Comment by PavelPolyakov** [comment]
now it's good, first it was based on `req.raw.originalUrl` and it seems it disappeared in `fastify v3`, however `req.url` should be compatible with `v2` and `v3`

**Comment by mcollina** [comment]
Thanks for figuring it out. We are preparing for the Fastify v3 release and we have landed that change in the meanwhile.

**Comment by mcollina** [comment]
@Eomm can you take a look as well?

**Comment by PavelPolyakov** [comment]
👋 @Eomm @mcollina would you be so kind to release another version of the `fastify-swagger@2` branch, which includes this fix?

`fastify v3` is not even released, and I can't use `fastify-swagger@3` with my correct `fastify v2` project because it requires `fastify v3`.

**Comment by Eomm** [comment]
I will do later today after work 👍🏼

**Comment by Eomm** [comment]
2.6.0 released in `2.x` branch

**Pull request merged**
