### PR TITLE
chore (ci): migrate ci to fastify plugins reusable workflows

### PR DESCRIPTION
**Pull request by darkgl0w**
Hello.

This PR aims to :
- add some npm scripts (improves DX and CI task splitting)
- run CI linter only once
- migrate to fastify plugins reusable workflow
- remove coveralls and check coverage with `tap` (enforcing 100% code coverage)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — CHANGES_REQUESTED** [review]
Could we migrate this repo to the new centalized worfflow?

It would be cool to:

- add the "1 lint runs" on the main flow https://github.com/fastify/workflows/
- reference the flow here (example: https://github.com/fastify/fastify-autoload/pull/216 )

**Comment by darkgl0w** [comment]
@Eomm > sure I will take a look to do so.

I will create a linter "standalone" workflow so that we should be able to use it like this :
```yml
name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  linter:
    uses: fastify/workflows/.github/workflows/linter-ci.yml@v2

  test:
    needs: linter
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v2
```

**Comment by darkgl0w** [comment]
On hold.
I will wait for reviews and suggestions on https://github.com/fastify/workflows/pull/10 to see how this PR should progress.

**Review by Eomm — APPROVED** [review]

**Pull request merged**
