### PR TITLE
Fixes for fastify v2

### PR DESCRIPTION
**Pull request by cemremengu**
Tests fail but I couldn't figure out. The redirect for `/documentation` -> `/documentation/index.html` does not return any payload for some reason

Failing test: https://github.com/fastify/fastify-swagger/blob/master/test/route.js#L286

Failing line: https://github.com/fastify/fastify-swagger/blob/master/routes.js#L14

Any ideas?

### CODE REVIEW

**Comment by mcollina** [comment]
@cemremengu this should fix the test!

**Comment by mcollina** [comment]
what’s the status of this?

**Comment by cemremengu** [comment]
Was waiting for #137 for covering more functionality. Should we land?

**Comment by mcollina** [comment]
I think so.

**Pull request merged**
