### PR TITLE
Type fixes for Fastify v3

### PR DESCRIPTION
**Pull request by MichielDeMey**
This fixes the types to be compatible with Fastify v3.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
We should probably update the types tests as well.

**Comment by MichielDeMey** [comment]
For that we'd have to upgrade Fastify in the `package.json`. What would be the best way forward?
Given that there is no pre-release yet, I can add it as a git repo using the `next` branch. (e.g. `"fastify": "github:fastify/fastify#next"`)

What do you think?

**Comment by mcollina** [comment]
I'm not going to land this on master until v3 is out. We can land this in a `next` branch.

**Comment by patarapolw** [comment]
But v3 is already out?

Where do I get `next` branch? `npm i fastify/fastify-swagger@xxx`?

**Comment by mcollina** [comment]
This got out of date. Install the latest version of fastify and fastify-swagger and things should work.

**Comment by patarapolw** [comment]
> Supports Fastify versions >=2.0.0. Please refer to this branch and related versions for Fastify ^1.9.0 compatibility.

You should update the README. It is confusing whether it supports Fastify v3 or not.

**Pull request closed without merging**
