### PR TITLE
Add persistAuthorization swagger ui option

### PR DESCRIPTION
**Pull request by santiagosemhan**
SwaggerUI has the ability to persist the authorization header into the local storage. Currently, our types don't support it.
This PR adds the property to `FastifySwaggerUiConfigOptions` type.

Reference: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Please add a typing test for this change.

**Comment by santiagosemhan** [comment]
> Please add a typing test for this change.

Let me know if it works

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
Do we need to add this option to the Readme.md?

**Comment by mcollina** [comment]
I don't think it's needed

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
