### PR TITLE
ci: enable license checking

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/workflows/issues/49

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@Fdawgs 
@mcollina 

`ackage "argparse@2.0.1" is licensed under "Python-2.0" which is not permitted by the --onlyAllow flag. Exiting.`

**Comment by mcollina** [comment]
where are we using this?

**Comment by Uzlopak** [comment]
@mcollina 

js-yaml

**Comment by Fdawgs** [comment]
May be worth replacing `js-yaml` with another package?

**Comment by mcollina** [comment]
We should switch to https://www.npmjs.com/package/yaml instead.

**Pull request merged**
