### PR TITLE
Adds support for OAS 3.0.0

### PR DESCRIPTION
**Pull request by nileshmali**
Adds support for OAS 3.0.0.

Fixes: #4

### CODE REVIEW

**Comment by mcollina** [comment]
There are a lot of changes that are only about code formatting, can you please restore them as they were before?

**Comment by nileshmali** [comment]
Sure. I will update.

**Comment by zenflow** [comment]
@nileshmali Not sure what I'm missing here... What does OpenAPI Specification 3 have to do with issue #4 titled "Hmm... Find a hard code here"?

(Btw I think #4 can be closed, see comment there)

**Comment by nileshmali** [comment]
@zenflow When I opened PR #4 was open. This PR adds support for OAS 3 and also fixes #4 plus this uses swagger-ui-dist to display swagger-ui.

**Comment by nileshmali** [comment]
I will submit separate pull requests for each OAS 3 support and use of swagger-ui-dist.

**Comment by zenflow** [comment]
@nileshmali Ahh I see.. the PR aimed at adding OAS 3 support and just incidentally you fixed #4.. cool

I think I see the value of adding OAS 3 support, but what is the value of using swagger-ui-dist? (May be good to put your answer in an issue)

**Pull request closed without merging**
