### PR TITLE
fix: include swagger extensions if define at the root

### LINKED ISSUE #304: Swagger extension are not included if defined at the root
## 🐛 Bug Report

[Swagger extensions](https://swagger.io/docs/specification/2-0/swagger-extensions/) are not supported at the root of the spec

## To Reproduce

This code

```typescript
import fastifySwagger from "fastify-swagger";
fastify.register(fastifySwagger, { swagger: { "x-tension": "test" } });
```

throw a type error

```
Type '{ "x-tension": string; }' is not assignable to type 'Partial<Spec>'.
      Object literal may only specify known properties, and '"x-tension"' does not exist in type 'Partial<Spec>'
```

and I can verify that the extension is not included in the documentation.

## Your Environment

- *node version*: 12
- *fastify version*: ^3.4.1
- *os*: Mac

### PR DESCRIPTION
**Pull request by thomasthiebaud**
Fixes #304, but I'm not super fan of the implementation. 

I'm missing an update on the type definitions, but I can't express `Partial<SwaggerSchema.Spec>` and properties starting by `x-`. Do you have any preferences about what to do with that?

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
> Do you have any preferences about what to do with that?

I can't answer per TS, waiting @zekth

**Comment by zekth** [comment]
One solution would be to set the swagger type to:
```ts
  swagger?: Partial<SwaggerSchema.Spec | Record<string,unknown>>;
```
Currently it's not possible but there is hope it will be in TypeScript 4.1. This example is not working yet but you get the idea.

Example: 
in playground: https://www.typescriptlang.org/play?target=99&ts=4.1.0-dev.20201001
```typescript
type prefixProperty<T extends string> = `${T}${string}`;
const test1: prefixProperty<'x-'> = 'x-ternal';
const test2: prefixProperty<'x-'> = 'ternal';
type prefixedObject<K extends prefixProperty<'x-'>,T> = { [P in K]:T}
const f: prefixedObject<prefixProperty<'x-'>,unknown> = {
    'x-bla': 'bar'
}
const d: prefixedObject<prefixProperty<'x-'>,unknown> = {
    'bla': 'bar'
}
const c: Record<prefixProperty<'x-'>,string> = {
    'x-bla': 'bar',
    'bla': 'bar'
}
```
Reference: https://github.com/microsoft/TypeScript/pull/40336

Mentionning @Ethan-Arrowood @fox1t @L2jLiga because we were talking about those templates earlier in fastify

**Comment by fox1t** [comment]
@zekth, the playground link is not working.

Said that, as of today, since TS is a type system that doesn't check the vars' values, I would leave the types as is. I am not even sure that it is correct to introduce this type of check at compile time in the future.

**Comment by L2jLiga** [comment]
I'm agree with @fox1t and also would keep as is

**Comment by zekth** [comment]
fair point @fox1t

**Comment by mcollina** [comment]
Any updates on this?

**Comment by thomasthiebaud** [comment]
Do you want me to rebase? Based on the discussion I don't need to add anything to the current PR then

**Comment by mcollina** [comment]
Could you just rebase? Thanks!

**Review by fox1t — APPROVED** [review]
LGTM

**Review by zekth — APPROVED** [review]
lgtm

**Pull request merged**
