### PR TITLE
Add OpenAPI Links support

### PR DESCRIPTION
**Pull request by mcollina**
As titled, this PR adds support for OpenAPI Links. This feature is OpenAPI v3 specific.
I did a somewhat different approach as it is not part of the schema.
Let me know if the place where I put those new options is ok or not.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
Can we add a warning message for `swagger`, so they will know that it is not supported when dev?

**Comment by mcollina** [comment]
> Can we add a warning message for `swagger`, so they will know that it is not supported when dev?

done

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by zekth — APPROVED** [review]
LGTM :)

**Pull request merged**
