### PR TITLE
fix: add hideUntagged to type definition

### PR DESCRIPTION
**Pull request by GaryGSC**
This should be really easy to review. 🙂

Refs: #406

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by zekth — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Divlo** [comment]
Could you release a new version with this change, please ? @mcollina 
Thanks for your work! :smile:

**Pull request merged**
