### PR TITLE
Updates for Fastify v5 

### PR DESCRIPTION
**Pull request by giovanniruzzi**
### What
* Update to fastify workflow v4.1.0
* Update dependencies to latest major versions
* Update unit tests

### Why
This PR aims to prepare fastify-swagger for the next version of fastify v5.

### Todo
- [ ] Validate changes on unit test

### CODE REVIEW

**Comment by giovanniruzzi** [comment]
I'd like to point out key changes in the unit tests. The upgrade to tap v18.5.6 means stricter `strictSame` checks. Often, schema properties now have an extra parameter `[Symbol('json-schema-resolver.ignore')]: true`, from [json-schema-resolver ref-resolver.js](https://github.com/Eomm/json-schema-resolver/blob/main/ref-resolver.js#L8). Tap v16 used [libtap](https://github.com/tapjs/libtap), but tap v18 uses `tcompare`, which is stricter about assertions. I had to use 't.match' instead of 't.strictSame'. I'm considering eliminating the Symbol somehow. Looking for guidance. 
Thanks

**Comment by simoneb** [comment]
> I'd like to point out key changes in the unit tests. The upgrade to tap v18.5.6 means stricter `strictSame` checks. Often, schema properties now have an extra parameter `[Symbol('json-schema-resolver.ignore')]: true`, from [json-schema-resolver ref-resolver.js](https://github.com/Eomm/json-schema-resolver/blob/main/ref-resolver.js#L8). Tap v16 used [libtap](https://github.com/tapjs/libtap), but tap v18 uses `tcompare`, which is stricter about assertions. I had to use 't.match' instead of 't.strictSame'. I'm considering eliminating the Symbol somehow. Looking for guidance. Thanks

I think `t.match` is an acceptable alternative

**Comment by gurgunday** [comment]
Hey, any updates?

You can use t.match or an alternative and we will review

**Comment by giovanniruzzi** [comment]
@gurgunday updated
sorry for the long wait

**Review by gurgunday — APPROVED** [review]

**Comment by gurgunday** [comment]
Thanks!

**Pull request merged**
