### PR TITLE
Add definitions models support

### PR DESCRIPTION
**Pull request by heyas**
I have added definitions support. All test passes. Plz add this.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by heyas** [comment]
I'm not sure about how right i do that.

**Comment by delvedor** [comment]
@heyas checkout how we are doing the other [tests](https://github.com/fastify/fastify-swagger/blob/master/test/swagger.js) :)

**Comment by heyas** [comment]
@delvedor Now i moved definitions to a separate test called 'fastify.swagger definitions'. In /documentation it looks like that:

image

**Comment by heyas** [comment]
Wow! That is my first pull request to open-source project! And i'll be very grateful if you publish it to npm.

**Comment by mcollina** [comment]
it is already out v0.11
Il giorno sab 19 mag 2018 alle 12:38 heyas <notifications@github.com> ha
scritto:

**Pull request merged**
