### PR TITLE
fix: undefined uiConfig

### PR DESCRIPTION
**Pull request by zekth**
Fix: https://github.com/fastify/fastify-swagger/issues/362

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by climba03003** [comment]
`uiConfig` should not be undefined.
See the below two snippets.
https://github.com/fastify/fastify-swagger/blob/master/lib/mode/dynamic.js#L19-20
https://github.com/fastify/fastify-swagger/blob/master/lib/mode/static.js#L64

**Comment by climba03003** [comment]
For `static` mode it is fixed in #356 which version is `4.2.0`.

**Comment by zekth** [comment]
My bad. Closing.

**Pull request closed without merging**
