### PR TITLE
Add produces field to FastifySchema definition

### LINKED ISSUE #468: Missing "produce" field in FastifySchema definition
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.0

### Plugin version

4.12.0

### Node.js version

16.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Docker node:16

### Description

FastifySchema interface definition should include a `produces` field with type `string[]` (same as `consumes`)
https://github.com/fastify/fastify-swagger/blob/1758a5ea8679cdbaef21ea81fda5cc02725515bc/index.d.ts#L18-L29

At the moment specifying this filed causes TypeScript to show the following error:
```
(...) Object literal may only specify known properties, and 'produces' does not exist in type 'FastifySchema'.

The expected type comes from property 'schema' which is declared here on type 'RouteShorthandOptions<Server, IncomingMessage, ServerResponse, { Params: ReduceModifiers<StaticModifiers<{ folderShortId: TString; }>> & ReduceModifiers<...>; }, unknown, FastifySchema>'
```

### Steps to Reproduce

```ts
import { Type } from '@sinclair/typebox';

server.get('/image.webp', {
  schema: {
    produces: ['image/webp'], // (...) Object literal may only specify known properties, and 'produces' does not exist in type 'FastifySchema'.
    response: {
      200: Type.String({
        format: 'binary',
      }),
    },
  },
}, async (request, reply) => {
  reply.type('image/webp').send(fse.createReadStream('/example-path'));
});
  ```

### Expected Behavior

No TypeScript error, `produces` field is `?: string[]`.

### PR DESCRIPTION
**Pull request by dominik-korsa**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

fixes #468

### CODE REVIEW

**Review by climba03003 — APPROVED** [review]
LGTM. I will wait until coveralls maintains over.

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you add an unit test for `produces` fields?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
