### PR TITLE
docs(readme): revamp documentation

### PR DESCRIPTION
**Pull request by Fdawgs**
As highlighted by https://github.com/fastify/fastify-swagger/issues/397#issuecomment-816660852, the documentation for `fastify-swagger` is quite long (my scroll wheel gets a good workout going through it). This PR attempts to resolve this issue by removing or consolidating parts where possible, as well as improving the readability.

This PR changes the following:

- Removes excess example JavaScript and JSON objects used to convey functionality that a single sentence could
- Add `routePrefix` option to Register Options table (removing need for separate section)
- Removes "Security" section (The introducing sentence of the OpenAPI specification states it is purely for documentation, I do not think we need to repeat them)
- Rewrite of certain sentences and paragraphs to improve flow/readability
- Grammatical fixes
- Fixes headers and grouping of sections by headers (register and response primarily)
- Consolidates "See Also" section into introduction
- Reduces length by ~100 lines

The "Integration" section still needs tidying  (perhaps being renamed to Content Security Policy Configuration and including @climba03003's CSP changes?)

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
I think it should split into multiple files and put it in a folder call `docs`.
This package is growing as the OpenAPI standard is growing and it is hard to write all feature in a single short document.

**Comment by Fdawgs** [comment]
> I think it should split into multiple files and put it in a folder call `docs`.
> 
> This package is growing as the OpenAPI standard is growing and it is hard to write all feature in a single short document.

Sounds good, thoughts on how it should be split? One register options, router options, and another for everything else?

**Comment by climba03003** [comment]
> 
> 
> > I think it should split into multiple files and put it in a folder call `docs`.
> > This package is growing as the OpenAPI standard is growing and it is hard to write all feature in a single short document.
> 
> Sounds good, thoughts on how it should be split? Register options, router options, and another for everything else?

I would go for this 5 big topic first. You can split it in other way.
1. Static Mode
2. Dynamic Mode - OpenAPI 3.0
3. Dynamic Mode - Swagger 2.0
4. Content Security Policy
5. Integration - fastify-helmet and fastify-multipart

**Comment by Fdawgs** [comment]
@climba03003 Not 100% I'll have time to break this up anytime soon, so I think it'd be better if this was committed, then broken up at a later date.

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
