### PR TITLE
add swagger-ui vendor extensions, esp. x-tokenName

### LINKED ISSUE #654: typing issue trying to add x-tokenName prop on securitySchemes
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

the swagger ui library, allows to configure the fieldname that will contain the jwt_token value on the auth response, using the prop `x-tokenName` on any of the securitySchemas, but the used typings on the project (`openapi-types`) does not have the definitions, giving us a type error.

```ts
 securitySchemes: {
  myAuth: {
    type: 'oauth2',
    'x-tokenName': 'my_custom_property', // * custom field name
    flows: {
      implicit: {
        authorizationUrl: `http.../login/oauth/authorize`,
        scopes: {},
      },
    },
  },
```  
workaround: cast your security scheme to `<any>`
```ts
 securitySchemes: {
  myAuth: <any>{
    type: 'oauth2',
    'x-tokenName': 'my_custom_property', // * custom field name
    flows: {
      implicit: {
        authorizationUrl: `http.../login/oauth/authorize`,
        scopes: {},
      },
    },
  },
```  

### Steps to Reproduce

use `x-tokenName` on a securityScheme definition 

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by Uzlopak**
Closes #654 

This PR adds the swagger ui vendor extensions x-tokenName.

There are two extensions. x-example and x-tokenName.

x-example does not need patching, because it is already covered by openapi-types. But I added typings tests to ensure, that they are possible. Didnt want that somebody comes tomorrow and says, they are missing... ;)

So this adds x-tokenName to the SecuritySchemas of OpenAPI v2 and v3.

ref: https://github.com/swagger-api/swagger-ui/pull/2587 (adding x-tokenName to OpenAPI2 in swagger-ui)
ref: https://github.com/swagger-api/swagger-js/pull/1489 (adding x-tokenName to OpenAPI3 in swagger-ui)

@fernandolguevara 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@mcollina 

I guess, when this gets merged, we need a release...

**Comment by fernandolguevara** [comment]
Nice!

it would be nice to have all the definitions for the swagger ui custom fields, but I think we need to dig in on the ui code to find them.

**Comment by Uzlopak** [comment]
@fernandolguevara 

Well, according to the swagger ui documentation only x-tokenName and x-example were named as vendor extensions. Also in the code only those tokens are prefixed with "x-".

So i dont think, there are more special tokens (atleast at this time).

**Comment by fernandolguevara** [comment]
thanks! =)

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
